### ISSUE TITLE
The prop type is invalid.

### ISSUE THREAD

**Issue by kimyearho** [P3trur0/vue-niege#1]
Hi!
The guide in the README document is invalid. The "speed" and "zIndex" of the props resource must be specified as a string.
There is no problem with the operation, but the following error occurs.

![image](https://user-images.githubusercontent.com/17153380/49889127-14a07b80-fe84-11e8-9870-48946fe41875.png)

![image](https://user-images.githubusercontent.com/17153380/49889146-208c3d80-fe84-11e8-8f8d-3f7b0372f381.png)

You need to make the following changes:
You must remove the v-bind for "zIndex" and "speed".

![image](https://user-images.githubusercontent.com/17153380/49889567-364e3280-fe85-11e8-979f-237dfb8e5b1a.png)

It now displays normally without errors.

**Comment by ubaldop** [comment]
@kimyearho thank you, nice spot! It has been fixed.
